### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by rimmesbe** [blues2017/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project. The code was well organized and well thought out. The main issue was just that your doing too much work. Use css to make your life easier, uses classes for reusable code, use general selectors to assign styling in 1 place. It takes practice and you did have good selectors usage in general. 
Here's a good css cheatsheet for some useful selectors that can help make your code more efficient. https://adam-marsden.co.uk/css-cheat-sheet/

**Comment by blues2017** [comment]
Hi Ryan, thanks very much for your feedback. All your points make sense and will update my code accordingly as this will greatly help moving forward.
